all: true
disable-version-string: true
outpkg: 'mocks'
dir: '{{.InterfaceDir}}/mocks'
packages:
  github.com/crowci/autoscaler/providers/hetznercloud/hcapi:
    config:
      recursive: true
  github.com/crowci/autoscaler/engine:
    config:
      recursive: true
  github.com/crowci/autoscaler/server:
    config:
      recursive: true
