when:
  - event: pull_request
  - event: push
    branch:
      exclude: ${CI_REPO_DEFAULT_BRANCH}

variables:
  - &golang_image 'golang:1.23'
  - &when
    - path: &when_path # related config files
        - '.woodpecker/test.yml'
        - '.golangci.yml'
        # go source code
        - '**/*.go'
        - 'go.*'
        # schema changes
        - 'pipeline/schema/**'
      branch:
        exclude: ${CI_REPO_DEFAULT_BRANCH}
      event: push
    - path: *when_path
      event: [pull_request, tag, deployment]

steps:
  lint:
    image: *golang_image
    depends_on: []
    commands:
      # install just FIXME: 'apt install -y just' from Debian >= 13
      - curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to /usr/bin/
      - just lint
    when: *when

  lint-editorconfig:
    image: mstruebing/editorconfig-checker:v3.1.2
    depends_on: []

  test:
    image: *golang_image
    depends_on: []
    commands:
      # install just FIXME: 'apt install -y just' from Debian >= 13
      - curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to /usr/bin/
      - just test
    when: *when
